<form data-mage-init='{"validation": {}, "Magento_Theme/js/widget": {}}'>
    <fieldset class="fildset">
        <div class="field required">
            <label for="name" class="label">
                Ім'я
            </label>
            <div class="control">
                <input
                    id="name"
                    type="text"
                    class="text-input"
                    data-validate="{required: true, 'validate-text-field': true}"
                >
            </div>
        </div>

        <div class="field required">
            <label for="surname" class="label">
                Прізвище
            </label>
            <div class="control">
                <input
                    id="surname"
                    type="text"
                    class="text-input"
                    data-validate="{required: true, 'validate-text-field': true}"
                >
            </div>
        </div>

        <div class="field">
            <label for="phone" class="label">
                Номер телефону
            </label>
            <div class="control">
                <input
                    id="phone"
                    type="tel"
                    class="text-input"
                >
            </div>
        </div>
    </fieldset>
</form>
