<div class="select-example">
    <label for="multiselect" class="label"><span><?php /* @escapeNotVerified */ echo __('Select example') ?></span></label>
    <select id="multiselect" name="multiselect-field" multiple="multiple">
        <option value="1">Option 1</option>
        <option value="2">Option 2</option>
        <option value="3">Option 3</option>
        <option value="4">Option 4</option>
        <option value="5">Option 5</option>
        <option value="6">Option 6</option>
    </select>
    <script>
        require(['jquery', 'mage/multiselect'], function ($) {
            $('#multiselect').multiselect2({selectedValues: [2, 4]});
        });
    </script>
</div>
